// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gmiaqmgqjxfzhsvsclzl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdtaWFxbWdxanhmemhzdnNjbHpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2MDQ3ODMsImV4cCI6MjA3NDE4MDc4M30.wGQ8eN3N8GY2YAlWCtqy6AcYIsEr0Eem5QCKTPtTe_E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});